LPS-195477 Create package Util
Valmir-unicap/liferay-portal pull request #39
Opened 2023-09-06 18:32 UTC by Valmir-unicap

2023-09-06 20:58 UTC, MrJohn1911 requested changes

2023-09-06 20:58 UTC, MrJohn1911 commented on modules/apps/mentions/mentions-service/src/main/java/com/liferay/mentions/internal/util/DefaultMentionsNotifier.java
> +	private class MentionsMatcherRegistry {
You don't need to create a class here, just put the method `getMentionsMatcher` inside the `DefaultMentionsNotifier` class.

2023-09-06 20:58 UTC, MrJohn1911 commented on modules/dxp/apps/analytics/analytics-reports-web/src/main/java/com/liferay/analytics/reports/web/internal/info/item/provider/util/AnalyticsReportsInfoItemObjectProviderRegistryUtil.java
> +	private static BundleContext _bundleContext;
Please remove this field and get the bundleContext using FrameworkUtil inside the static block.

2023-09-08 19:19 UTC, rafaprax requested changes

2023-09-08 19:19 UTC, rafaprax commented on modules/apps/analytics/analytics-settings-impl/src/main/java/com/liferay/analytics/settings/internal/configuration/AnalyticsConfigurationRegistryImpl.java
> +		_bundleContext = bundleContext;
you don't need the `_bundleContext ` variable

2023-09-11 18:12 UTC, rafaprax approved these changes

2023-09-11 18:16 UTC, closed without merging