LPS-194841 Remover component from PathInterpreter, create constructor, and apply to usages
Valmir-unicap/liferay-portal pull request #43
Opened 2023-09-22 20:14 UTC by Valmir-unicap

2023-09-22 20:14 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-25 17:28 UTC, Valmir-unicap commented
ci:test:sf

2023-09-25 17:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/7151/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7151/jenkins-report.html">here</a>.</b></p>

2023-09-25 17:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33dcc7116256d2c52b3a676d48e7ed3276320ed4">33dcc7116256d2c52b3a676d48e7ed3276320ed4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-194841-Refactor">LPS-194841-Refactor</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/8f857214a4de28682a1cd0645e0efe37838775a3">8f857214a4de28682a1cd0645e0efe37838775a3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7151/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7151/jenkins-report.html">here</a>.</h5></details></html>

2023-09-25 17:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/7151/">test-portal-source-format#7151</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/7151/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Valmir-unicap/liferay-portal/pull/43">Valmir-unicap#43</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430544554">[master] ci:test:sf - Valmir-unicap &gt; Valmir-unicap - PR#43 - 2023-09-25[10:29:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/4402/">publish-testray-report#4402</a><br/></div></div>

2023-09-25 18:46 UTC, Valmir-unicap commented
ci:test:sf

2023-09-25 18:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7458/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7458/jenkins-report.html">here</a>.</b></p>

2023-09-25 18:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/33dcc7116256d2c52b3a676d48e7ed3276320ed4">33dcc7116256d2c52b3a676d48e7ed3276320ed4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-194841-Refactor">LPS-194841-Refactor</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/8d1ec935528263b332ce868887793789b4d66b62">8d1ec935528263b332ce868887793789b4d66b62</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7458/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7458/jenkins-report.html">here</a>.</h5></details></html>

2023-09-25 18:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7458/">test-portal-source-format#7458</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7458/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Valmir-unicap/liferay-portal/pull/43">Valmir-unicap#43</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2430554258">[master] ci:test:sf - Valmir-unicap &gt; Valmir-unicap - PR#43 - 2023-09-25[11:47:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4612/">publish-testray-report#4612</a><br/></div></div>

2023-09-26 18:24 UTC, rafaprax requested changes

2023-09-26 18:24 UTC, rafaprax commented on modules/apps/sharing/sharing-web/src/main/java/com/liferay/sharing/web/internal/interpreter/AssetRendererSharingEntryInterpreter.java
> +			new AssetRendererSharingEntryEditRenderer();
@Valmir-unicap, you do not need to do those "reinitializations". Please remove.

2023-09-26 18:26 UTC, rafaprax requested changes

2023-09-26 18:26 UTC, rafaprax commented on modules/apps/sharing/sharing-web/src/main/java/com/liferay/sharing/web/internal/interpreter/SharingEntryInterpreterProviderImpl.java
>  	private AssetRendererSharingEntryInterpreter
Please initialize this field.

2023-09-26 21:33 UTC, Valmir-unicap commented
see https://github.com/Valmir-unicap/liferay-portal/pull/44

2023-09-26 21:33 UTC, closed without merging