LPS-194841 Remove component PathInterpreter, create constructor, and apply to usages
Valmir-unicap/liferay-portal pull request #44
Opened 2023-09-26 21:32 UTC by Valmir-unicap

2023-09-26 21:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-26 21:32 UTC, Valmir-unicap commented
ci:test:sf

2023-09-26 21:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-source-format/7254/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7254/jenkins-report.html">here</a>.</b></p>

2023-09-26 21:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f9372b7b8b33f963988bb7155f88bdbbcc7154da">f9372b7b8b33f963988bb7155f88bdbbcc7154da</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-194841-Conclued">LPS-194841-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/a0fab93c994ed9a2698a6c7126abadffd8af3973">a0fab93c994ed9a2698a6c7126abadffd8af3973</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7254/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7254/jenkins-report.html">here</a>.</h5></details></html>

2023-09-26 21:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/7254/">test-portal-source-format#7254</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/7254/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Valmir-unicap/liferay-portal/pull/44">Valmir-unicap#44</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2431795422">[master] ci:test:sf - Valmir-unicap &gt; Valmir-unicap - PR#44 - 2023-09-26[14:33:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/3443/">publish-testray-report#3443</a><br/></div></div>

2023-10-02 17:09 UTC, Valmir-unicap commented
ci:test:sf

2023-10-02 17:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7441/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7441/jenkins-report.html">here</a>.</b></p>

2023-10-02 17:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a93daf3fd852d2730ebe63a3c5ecf9ad49078593">a93daf3fd852d2730ebe63a3c5ecf9ad49078593</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-194841-Conclued">LPS-194841-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/e9589791ccd1d3a95627284d37aca2f9cc03b16e">e9589791ccd1d3a95627284d37aca2f9cc03b16e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7441/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7441/jenkins-report.html">here</a>.</h5></details></html>

2023-10-02 17:15 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7441/">test-portal-source-format#7441</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7441/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Valmir-unicap/liferay-portal/pull/44">Valmir-unicap#44</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434677622">[master] ci:test:sf - Valmir-unicap &gt; Valmir-unicap - PR#44 - 2023-10-02[10:09:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27783/">publish-testray-report#27783</a><br/></div></div>

2023-10-02 18:45 UTC, MrJohn1911 requested changes

2023-10-02 18:45 UTC, MrJohn1911 commented on modules/apps/sharing/sharing-web/src/main/java/com/liferay/sharing/web/internal/interpreter/SharingEntryInterpreterProviderImpl.java
> +	private final AssetRendererSharingEntryInterpreter
Please initialize this field in the activate method.

2023-10-02 18:45 UTC, MrJohn1911 commented on modules/apps/adaptive-media/adaptive-media-image-impl/src/main/java/com/liferay/adaptive/media/image/internal/handler/AMImageRequestHandler.java
> +	private final PathInterpreter _pathInterpreter = new PathInterpreter(
Please initialize this field in the activate method.

2023-10-02 18:45 UTC, MrJohn1911 commented on modules/apps/adaptive-media/adaptive-media-image-impl/src/test/java/com/liferay/adaptive/media/image/internal/handler/PathInterpreterTest.java
> +		_amImageConfigurationHelper, _dlAppService);
Please initialize this field in the activate method.

2023-10-02 19:22 UTC, Valmir-unicap commented
ci:test:sf

2023-10-02 19:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a93daf3fd852d2730ebe63a3c5ecf9ad49078593">a93daf3fd852d2730ebe63a3c5ecf9ad49078593</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-194841-Conclued">LPS-194841-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/66ad1117b7009ba306644dc9e16c6fcf34412a9a">66ad1117b7009ba306644dc9e16c6fcf34412a9a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1825/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1825/jenkins-report.html">here</a>.</h5></details></html>

2023-10-02 19:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1825/">test-portal-source-format#1825</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1825/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Valmir-unicap/liferay-portal/pull/44">Valmir-unicap#44</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2434748689">[master] ci:test:sf - Valmir-unicap &gt; Valmir-unicap - PR#44 - 2023-10-02[12:23:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/4351/">publish-testray-report#4351</a><br/></div></div>

2023-10-04 18:20 UTC, Valmir-unicap commented
ci:test:sf

2023-10-04 18:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3116/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3116/jenkins-report.html">here</a>.</b></p>

2023-10-04 18:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f896c21dffb4913f9a7ac72f32bb565c89ae4f24">f896c21dffb4913f9a7ac72f32bb565c89ae4f24</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-194841-Conclued">LPS-194841-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/e410509218f1544b815278b8459024fa890dc1b0">e410509218f1544b815278b8459024fa890dc1b0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3116/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3116/jenkins-report.html">here</a>.</h5></details></html>

2023-10-04 21:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3116/">test-portal-source-format#3116</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3116/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Valmir-unicap/liferay-portal/pull/44">Valmir-unicap#44</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2436597931">[master] ci:test:sf - Valmir-unicap &gt; Valmir-unicap - PR#44 - 2023-10-04[11:21:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/12069/">publish-testray-report#12069</a><br/></div></div>

2023-10-06 18:07 UTC, rafaprax requested changes

2023-10-06 18:07 UTC, rafaprax commented on modules/apps/adaptive-media/adaptive-media-image-impl/src/test/java/com/liferay/adaptive/media/image/internal/handler/PathInterpreterTest.java
>  		ReflectionTestUtil.setFieldValue(
remove the reflection usage here

2023-10-13 16:42 UTC, rafaprax approved these changes

2023-10-13 16:45 UTC, Valmir-unicap commented
sent to the team repository

2023-10-13 16:45 UTC, closed without merging