LPS-198452 Inline class OrganizationTypeConfigurationWrapper in class OrganizationTypesSettingsImpl
Valmir-unicap/liferay-portal pull request #52
Opened 2023-10-10 17:09 UTC by Valmir-unicap

2023-10-10 17:09 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-11 16:05 UTC, Valmir-unicap commented
ci:test:sf

2023-10-11 16:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3214/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3214/jenkins-report.html">here</a>.</b></p>

2023-10-11 16:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e28d536cb8e3dfabbcadbb03ec7abdd3a10a1310">e28d536cb8e3dfabbcadbb03ec7abdd3a10a1310</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-198452">LPS-198452</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/7b8891808e5b3f424fdbef29e729ad6d37c148cc">7b8891808e5b3f424fdbef29e729ad6d37c148cc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3214/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3214/jenkins-report.html">here</a>.</h5></details></html>

2023-10-11 16:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3214/">test-portal-source-format#3214</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3214/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Valmir-unicap/liferay-portal/pull/52">Valmir-unicap#52</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2439839683">[master] ci:test:sf - Valmir-unicap &gt; Valmir-unicap - PR#52 - 2023-10-11[09:06:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/12413/">publish-testray-report#12413</a><br/></div></div>

2023-10-13 18:29 UTC, rafaprax requested changes

2023-10-17 19:46 UTC, Valmir-unicap commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/ElasticsearchIndexSearcher.java
> +	public int getPointInTimeKeepAliveSeconds() {
It is not possible to change to private, because this method is used in the test `ElasticsearchIndexSearcherSearchAfterTest.java`

2023-10-17 19:56 UTC, Valmir-unicap commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/ElasticsearchIndexSearcher.java
> +		_deepPaginationConfiguration = getDeepPaginationConfiguration(
It is not possible to change to private, because this method is used in the test ElasticsearchIndexSearcherSearchAfterTest.java

2023-10-17 19:57 UTC, Valmir-unicap commented on modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/ElasticsearchIndexSearcher.java
> +		long companyId) {
Corrected!

2023-10-18 21:13 UTC, closed without merging